(define (attach-tag type-tag . contents)
    (if (and (number? (car contents)) (null? (cdr contents)))
        (car contents)
        (cons type-tag contents)))
(define (type-tag datum)
    (cond ((number? datum) 'scheme-number)
        ((pair? datum) (car datum))
        (else (error "Bad tagged datum -- TYPE-TAG" datum))))
(define (contents datum)    ;   多个参数用cadr获得内容
    (cond ((number? datum) datum)
        ((pair? datum) (cadr datum))
        (else (error "Bad tagged datum -- CONTENTS" datum))))