(load "./2-46-Vector.scm")
(load "./2-47-make-frame.scm")
(define (frame-coord-map frame)
    (lambda (v) (add-vect (origin-frame frame)
                          (add-vect (scale-vect (xcor-vect v)
                                      (edge1-frame frame))
                                    (scale-vect (ycor-vect v)
                                                (edge2-frame frame))))))
; (define a-frame (make-frame (make-vect 1 1) (make-vect 2 0) (make-vect 0 3)))
; (origin-frame a-frame)
; ((frame-coord-map a-frame) (make-vect 0 0))