(load "P38-sum.scm")
(define (cube x)
          (* x x x))
(define (Simpson f a b n)
    (define h (/ (- b a) n))
    (define (term k)
        (cond ((or (= 0 k) (= n k))
                (f (+ a (* k h))))
            ((odd? k)
                (* 4 (f (+ a (* k h)))))
            (else
                (* 2 (f (+ a (* k h)))))))
    (define (next k)
        (+ k 1))
    (*  (/ h 3)
        (sum term (exact->inexact 0) next n)))
(trace simpson)
(Simpson cube 0 1 100)
(Simpson cube 0 1 1000)