(load "./p49-newton-method.scm")
(define (cube i)
    (* i i i))
(define (cubic a b c)
    (lambda (x) (+  (cube x)
                    (* a (square x))
                    (* b x)
                    c)))
(newtons-method (cubic 1 1 1) 1)