(define (make-segment s-point e-point)
    (cons s-point e-point))
(define (start-segment s)
    (car s))
(define (end-segment s)
    (cdr s))

(define (make-point x y)
    (cons x y))
(define (x-point p)
    (car p))
(define (y-point p)
    (cdr p))

(define (print-point p)
    (newline)
    (display "(")
    (display (x-point p))
    (display ",")
    (display (y-point p))
    (display ")"))

(define (midpoint-segment seg)
    (define (average a b)
        (/ (+ a b) 2))
    (let ((s (start-segment seg))
          (e (end-segment seg)))
        (make-point (average (x-point s) (x-point e))
                    (average (y-point s) (y-point e)))))

; (define row (make-point 0 3))
; (define col (make-point 4 0))
; (define third (make-segment row col))

; (print-point (midpoint-segment third))